build:
  maxIssues: 50

comments:
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: true
    excludes: [ '**/*.kt' ]
    includes: [ '**/detekt-api/src/main/**/api/*.kt' ]
  UndocumentedPublicFunction:
    active: true
    excludes: [ '**/*.kt' ]
    includes: [ '**/detekt-api/src/main/**/api/*.kt' ]

complexity:
  StringLiteralDuplication:
    active: true
    excludes: [ '**/test/**', '**/*.Test.kt', '**/*.Spec.kt' ]
    threshold: 5
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  ComplexInterface:
    active: true
    threshold: 30
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  ComplexMethod:
    active: true
    ignoreSingleWhenExpression: true
  MethodOverloading:
    active: true
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 30
    thresholdInInterfaces: 30
    ignorePrivate: true
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
  LongMethod:
    threshold: 150

exceptions:
  NotImplementedDeclaration:
    active: true
  InstanceOfCheckForException:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
  MemberNameEqualsClassName:
    active: true
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  TopLevelPropertyNaming:
    active: false
  MatchingDeclarationName:
    active: false

performance:
  ArrayPrimitive:
    active: true

potential-bugs:
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  MissingWhenCase:
    active: true
  RedundantElseInWhen:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
    excludes: [ '**/test/**', '**/*.Test.kt', '**/*.Spec.kt' ]
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  CollapsibleIfStatements:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: true
    values: [ 'TODO:', 'FIXME:', 'STOPSHIP:', '@author' ]
  FunctionOnlyReturningConstant:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: [ '**/*.kt' ]
    includes: [ '**/detekt-api/src/main/**/api/*.kt' ]
  MaxLineLength:
    excludes: [ '**/test/**', '**/*.Test.kt', '**/*.Spec.kt', '**/MainActivity.kt' ]
    excludeCommentStatements: true
  MagicNumber:
    active: false
  MayBeConst:
    active: true
  NestedClassesVisibility:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryInheritance:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected)'
  UseCheckOrError:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false